import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Logo from "@/components/logo";
import MainNav from "@/components/mainNav";
import { Toaster } from "react-hot-toast";
import Provider from "@/utils/provider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Internal application",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="grid grid-cols-[16rem,1fr] grid-rows-[auto,1fr] h-screen bg-[#161616]">
          <div className="flex flex-col justify-start gap-20 my-20 mx-5 ">
            <Logo />
            <MainNav />
          </div>
          <main className="p-16 pt-20 px-6 bg-[#2E2E2E] overflow-scroll w-full h-screen">
            <div className="max-w-[120rem] mx-0 my-auto flex flex-col gap-14 w-full">
              <Provider>
                {children}
              </Provider>
            </div>
          </main>
        </div>

        <Toaster
          position="top-center"
          gutter={12}
          containerStyle={{ margin: "8px" }}
          toastOptions={{
            success: { duration: 3000 },
            error: { duration: 5000 },
            style: {
              fontSize: "14px",
              maxWidth: "400px",
              padding: "14px 20px",
              backgroundColor: "#ffffff",
              color: "#898989",
            },
          }}
        />
      </body>
    </html>
  );
}
